name: Deploy Static Site to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy using ZipDeploy
        run: |
          curl -X POST -u "${{ secrets.ZIP_DEPLOY_USER }}:${{ secrets.ZIP_DEPLOY_PASSWORD }}" \
          --data-binary @site.zip \
          https://shop-on-the-f3gucncqgkgyatda.scm.azurewebsites.net/api/zipdeploy
